[project]
name = "project5-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lateeeppp", email = "ikhsannudin.dev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.99",
    "botocore>=1.43.99",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.8",
]
